spring:
  datasource:
    url: jdbc:mysql://mysql:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

shiro-redis:
  enabled: true
  redis-manager:
    host: redis:6379
  session-dao:
    expire: 3600